# Generated by Django 4.0.4 on 2022-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(max_length=100)),
                ('isbooked', models.BooleanField(default=False)),
                ('user_register', models.CharField(default=0, max_length=100)),
                ('date_time', models.CharField(default=0, max_length=100)),
                ('expiration', models.BooleanField(default=False)),
            ],
        ),
    ]
