# Generated by Django 4.0.3 on 2022-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=220)),
                ('phone', models.CharField(max_length=10)),
                ('psw', models.CharField(max_length=100)),
                ('issroommanager', models.BooleanField(default=False)),
            ],
        ),
    ]
