# Generated by Django 4.0.3 on 2022-04-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='psw',
        ),
    ]
