# Generated by Django 4.0.3 on 2022-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_users_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='psw',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
